
GET http://localhost:8000/api/ok/

###
GET http://localhost:8000/api/timeout

###

GET http://localhost:8000/api/users?limit=4

###

GET http://localhost:8000/api/metrics

###

GET http://localhost:8000/api/users/10

###

POST http://localhost:8000/api/books
Content-Type: application/json

{
  "id": 2,
  "title": "Sample Book",
  "author": "John Doe",
  "year": 2023
}

###

PUT http://localhost:8000/api/users/110
Content-Type: application/json

{
    "fullname": "Kevin"
}
###
DELETE http://localhost:8000/api/users/"9"

###

GET http://localhost:8000/api/profiles/




